#ifndef _CONFIG_H_
#define _CONFIG_H_

#define LEFT_DRIVE_MOTOR_LEFT_GPIO 16
#define LEFT_DRIVE_MOTOR_RIGHT_GPIO 4

#define RIGHT_DRIVE_MOTOR_LEFT_GPIO 22
#define RIGHT_DRIVE_MOTOR_RIGHT_GPIO 21

#define LEFT_JUMP_MOTOR_LEFT_GPIO 33
#define LEFT_JUMP_MOTOR_RIGHT_GPIO 32

#define RIGHT_JUMP_MOTOR_LEFT_GPIO 26
#define RIGHT_JUMP_MOTOR_RIGHT_GPIO 25


#endif